#+TITLE: Lab 4 MM5016
#+DATE: \today
#+OPTIONS: num:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:nil todo:t |:t
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: se
#+LaTeX_CLASS: notesse
#+LATEX_HEADER: \input{/home/john/texstuff/org/env.tex}
#+LATEX_HEADER: \input{/home/john/texstuff/org/bold.tex}
#+STARTUP: latexpreview


* Problems

** exe: System 1 :ignore:
#+LATEX: \begin{exercise}[System 1]  \label{exe:System_1}
Use Gaussian elimination to solve the system of linear equations
\begin{align*}
x_1 + 5x_2 = 7 \\
-2x_1 -7x_2 = -5
.
\end{align*}
#+LATEX: \end{exercise}


** sol:  :ignore:
#+LATEX: \begin{solution}[]  \label{sol:}
First step is to eliminate all \( x_1 \) under line 1. We do this by
adding an appropiate multiple of line 1 to the line we
want to eliminate \( x_1 \) from. In this case it means to add the first
line times 2 to second line. That yields the following system:
\begin{align*}
x_1 + 5x_2 = 7 \\
3x_2 = 9
.
\end{align*}

Our system is now overtriangular, which mean we can go into
the process of solving each equation by themselves by starting
from the bottom and substituting into the equation above
relative of the equation in question.


So we start by solving \( x_2 = 3  \) from the second equation. Next step is
to substitute this into the above equation and get the equation
\begin{align*}
x_1 + 15 = 7
.
\end{align*}

And thus we can from this equation solve that \( x_1 = -8 \).

#+LATEX: \end{solution}


** exe: System 2 :ignore:
#+LATEX: \begin{exercise}[System 2]  \label{exe:System_2}
Use Gaussian elimination to solve the system of linear equation
\begin{align*}
2x_2 + x_3 = -8 \\
x_1 - 2x_2 - 3x_3 = 0 \\
-x_1 + x_2 + 2x_3 = 3
.
\end{align*}
#+LATEX: \end{exercise}



** exe: System 3 :ignore:
#+LATEX: \begin{exercise}[System 3]  \label{exe:System_3}
Use Gaussian elimination to solve the system of linear equations
\begin{align*}
x_1 - 2x_2 -6x_3 = 12 \\
2x_1 + 4x_2 + 12x_3 = -17 \\
x_1 - 4x_2 - 12x_3 = 22
.
\end{align*}
#+LATEX: \end{exercise}

** sol:  :ignore:
#+LATEX: \begin{solution}[]  \label{sol:}
As in the previous system we start by eliminating all \( x_1 \) from
all the lines below the first line.
To eliminate \( x_1 \) from the second line we add \( -2 \) times the first line
to it. That yields the following equation:
\begin{align*}
8x_2 + 24x_3 = -41
.
\end{align*}

#+LATEX: \end{solution}
