#+TITLE: MM5016 Laboration 8 Error analysis
#+DATE: \today
#+OPTIONS: num:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:nil todo:t |:t
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: se
#+LaTeX_CLASS: notesse
#+LATEX_HEADER: \input{/home/john/texstuff/org/env.tex}
#+LATEX_HEADER: \input{/home/john/texstuff/org/bold.tex}
#+STARTUP: latexpreview

* Problems

** exe: 1 :ignore:
#+LATEX: \begin{exercise}[1]  \label{exe:1}
The two quantities \( x \) and \( y \) have a relative error
of \( \epsilon_x \) respectively \( \epsilon_y \). Calculate the error in the following cases:
1. \( x -2y \)
2. \( 4x -5y \)
3. \( 3xy \)
4. \( x^{3} / y^{5}  \)
5. \( \sqrt{x} \)
6. \( \sqrt{x^{3} } \)
7. \( \sqrt{2xy} \)
8. \( 2 \sqrt{\frac{x}{3y}} \)
9. \( 2 \sqrt{\frac{x^{3} }{3y}} \)
10. \( \frac{x}{y} + \frac{y}{x} \)
11. \( x^2 + y^2 \)
#+LATEX: \end{exercise}

** lem: error of scaled approximate value :ignore:
#+LATEX: \begin{lemma}[error of scaled approximate value] \label{lem:error_of_scaled_approximate_value}
Let \( x \) be a value and \( \tilde{x}  \) and approximation with relative error \( \epsilon _x \), and
\( \lambda \) a scalar. Then the relative error of \( \lambda \tilde{x}  \) is
\( \epsilon _{\lambda x } = \epsilon _{x} \). This is because \( \lambda \tilde{x} = \lambda x(1+ \epsilon _{\lambda x} ) \).
#+LATEX: \end{lemma}

** lem: error of exponent :ignore:
#+LATEX: \begin{lemma}[error of exponent] \label{lem:error_of_exponent}
Let \( x \) be a value and \( \tilde{x}  \) and approximation with relative
error \( \epsilon _{x} \), and \( a \) an integer. Then the relative error of
\( \tilde{x} ^{a}  \) is \( \epsilon _{x^{a} } = a \epsilon _{x} \). This is because
\( \epsilon _{x^{a} } = \epsilon _{x x^{a-1} } = \epsilon _{x} + \epsilon _{x^{a-1} } \) .
#+LATEX: \end{lemma}



** sol: 1 :ignore:
#+LATEX: \begin{solution}[1]  \label{sol:1}
(1)
\begin{align*}
\epsilon _{x - 2y} &   = \frac{x}{x - (2y) } \epsilon _{x} -
\frac{(2y) }{x - (2y) } \epsilon _{2y} \\
& = \frac{x}{x - 2 y } \epsilon _{x} -
\frac{2 y }{x - 2 y  } \epsilon _{y}
.
\end{align*}

(2)
\begin{align*}
\epsilon _{4x - 5y}  &  =
\frac{4x}{4x - 5y} \epsilon _{4x} - \frac{5y}{4x - 5y} \epsilon _{5y} \\
& = 
\frac{4x}{4x - 5y} \epsilon _{x} - \frac{5y}{4x - 5y} \epsilon _{y}
.
\end{align*}

(3)
\begin{align*}
\epsilon _{3xy} = \epsilon _{xy} = \epsilon _{x} + \epsilon _{y}
.
\end{align*}

(4)
\begin{align*}
\epsilon _{\frac{x^{3} }{y^{5} } } = \epsilon _{x^{3} } - \epsilon _{y^{5}} = 3 \epsilon _{x} - 5 \epsilon _{y}
.
\end{align*}

(5)
\begin{align*}
 &  \epsilon _{x} = \epsilon _{\sqrt{x}^{2}} = 2 \cdot\epsilon _{\sqrt{x}} \\
\implies & \epsilon _{\sqrt{x}} = \epsilon _{x} / 2
.
\end{align*}

(6)
\begin{align*}
\epsilon _{\sqrt{x^{3}}} = \frac{\epsilon _{x^{3}}}{2} = \frac{3}{2} \epsilon _{x}
.
\end{align*}
(7)
\begin{align*}
\epsilon _{\sqrt{2xy}}  &  = \epsilon _{\sqrt{2} \cdot  \sqrt{x} \cdot \sqrt{y}} \\
& = \epsilon _{\sqrt{x} \cdot  \sqrt{y}} = \epsilon _{\sqrt{x}} + \epsilon _{\sqrt{y}} \\
& = \frac{\epsilon _{x}}{2} + \frac{\epsilon _{y}}{2} 
.
\end{align*}

(7)
\begin{align*}
\epsilon _{2 \sqrt{ \frac{x^{3}}{3y}}}  &  = \epsilon _{\sqrt{ \frac{x^{3}}{3y}}}
= \frac{\epsilon _{\frac{x^{3}}{3y}}}{2} = \frac{\epsilon _{x^{3}} - \epsilon _{3y}}{2}
= \frac{3 \epsilon _{x} - \epsilon _{y}}{2} 
.
\end{align*}
(8)
\begin{align*}
\epsilon _{\frac{x}{y} + \frac{y}{x}}  &
= \frac{\frac{x}{y}}{\frac{x}{y} + \frac{y}{x}} \epsilon _{\frac{x}{y}}
+ \frac{\frac{y}{z}}{\frac{x}{y} + \frac{y}{x}} \epsilon _{\frac{y}{z}}
= \frac{x}{x + \frac{y ^2}{x}} \epsilon _{\frac{x}{y}}
+ \frac{y}{\frac{x}{yz} + \frac{y}{xz}} \epsilon _{\frac{y}{z}} \\
& = 
\frac{x}{x + \frac{y ^2}{x}} \epsilon _{\frac{x}{y}}
+ \frac{y}{\frac{x^2 + y ^2}{xyz}} \epsilon _{\frac{y}{z}} \\
& = 
\frac{x}{x + \frac{y ^2}{x}} \epsilon _{\frac{x}{y}}
+ \frac{x y ^2 z}{x^2 + y ^2} \epsilon _{\frac{y}{z}} \\
& = 
\frac{x ^2}{x ^2 + y ^2} \epsilon _{\frac{x}{y}}
+ \frac{x y ^2 z}{x^2 + y ^2} \epsilon _{\frac{y}{z}} \\
& =
\frac{x}{x ^2 + y ^2} (\epsilon _{\frac{x}{y}} + y ^2 z \epsilon _{\frac{y}{z}}) \\
& =
\frac{x}{x ^2 + y ^2} (\epsilon _{x} - \epsilon _{y} + y ^2 z (\epsilon _{y} - \epsilon _{z}))
.
\end{align*}

(8)
\begin{align*}
\epsilon _{x^2 + y^2}  &   = \frac{x ^2}{x^2 + y ^2} \epsilon _{x ^2} + \frac{y ^2}{x ^2 + y^2} \epsilon _{y ^2} \\
& = \frac{x ^2}{x^2 + y ^2} 2\epsilon _{x} + \frac{y ^2}{x ^2 + y^2} 2\epsilon _{y}
.
\end{align*}
#+LATEX: \end{solution}




** exe: 2 :ignore:
#+LATEX: \begin{exercise}[2]  \label{exe:2}
The radius of a sphere is \( R = (22.2 \pm 0.1)cm \). The radius
of the base of a cylinder is \( r= (12.0 \pm 1.2)cm \), and its
height is \( h=(24.4 \pm 1.1)cm \). What is the total volum
occupied by the sphere and by the cylinder (including the error)?
#+LATEX: \end{exercise}

** sol: 2 :ignore:
#+LATEX: \begin{solution}[2]  \label{sol:2}
Let the subscript \( t \) denote the true value.
\begin{align*}
V _{total}  &  = \frac{4 \pi}{3} (R + \delta R)^{3} + \pi (r+ \delta r) ^2 h \\
& = \frac{4 \pi}{3} (R^{3} + 3 R^2 \delta R + 3 R \delta R ^2 + \delta R^{3})
+ \pi (r ^2 + 2 \delta r+ \delta ^2) (h + \delta h) \\
& = \frac{4 \pi}{3} (R^{3} + 3 R^2 \delta R + 3 R \delta R ^2)
+ \pi (r ^2 + 2 \delta r) (h + \delta h) \\
& = \frac{4 \pi}{3} (R^{3} + 3 R^2 \delta R + 3 R \delta R ^2)
+ \pi (r ^2 h + r ^2 \delta h + 2 \delta h r + 2 \delta r \delta h) \\
& = \frac{4 \pi}{3} (R^{3} + 3 R^2 \delta R)
+ \pi (r ^2 h + r ^2 \delta h + 2r \delta h )
.
\end{align*}

To calculate the minimum volume we let the absolute be so much negative
as possible and the reverse for the maximum, if we plug in these values
we get:
\begin{align*}
55668.1 \leq V _{total} \leq 58068
.
\end{align*}


#+LATEX: \end{solution}

** Stuff :noexport:
#+begin_src python :results output :session
import math
R = 22.2
dR = 0.1
r = 12.0
dr = 1.2
h = 24.4
dh = 1.1

p1 = R ** 3 + 3 * (R ** 2) * dR
print("p1:", p1)
p2 = (r ** 2) * h + (r ** 2) * dh + 2 * r * dh
print("p2:", p2)

fp3 = (4 * math.pi) / 3
pi = math.pi
t = fp3 * p1 + pi * p2
print("t:", t)
#+end_src

#+RESULTS:
: p1: 11088.9
: p2: 3698.4
: t: 58067.9419718923

